kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: jenkins-robot
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["*", "*"]
    verbs: ["get", "watch", "list"]




