---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata: 
  name: "gradle-repo"
  namespace: "cloudbees-core"
spec: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
