apiVersion: v1
kind: Pod
metadata:
  name: test-dind
spec:
  containers:
  - name: dind
    image: benhall/dind-jenkins-agent
    command:
    - sleep
    args:
    - infinity
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: myvolume
  volumes:
  - name: myvolume
    hostPath:
      path: /var/run/docker.sock
      type: FileOrCreate    
